version: "3"
services:
  mysql:
    build: "./mysql/"
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/initdb:/docker-entrypoint-initdb.d"
      - "./log/mysql:/var/log/mysql"
    image: stylist_navi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "mysqladmin"
      MYSQL_PASSWORD: "password"
      TZ: "Asia/Tokyo"
