version: "3"
services:
  webserver:
    build:
      context: ../../
      dockerfile: ./docker/node/Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    image: stylist_navi_webapp
